### PR TITLE
Fixed #70: convert value to unicode to avoid encoding issues

### LINKED ISSUE #70: unicode support in formatter.py
Hello,

```
Name: python-logstash
Version: 0.4.6
Summary: Python logging handler for Logstash.
Home-page: https://github.com/vklochan/python-logstash
Author: Volodymyr Klochan
Author-email: vklochan@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

Using python-logstash through ansible logstash call back I get the following error:

```
TASK [java/jdk : Préparation répertoire destination Java] ***********************************************************************************************************************************************************************************
changed: [tnr-container]
TASK: java/jdk : Préparation répertoire destination Java
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 578, in emit
    s = self.makePickle(record)
  File "/usr/local/lib/python2.7/dist-packages/logstash/handler_tcp.py", line 25, in makePickle
    return self.formatter.format(record) + b'\n'
  File "/usr/local/lib/python2.7/dist-packages/logstash/formatter.py", line 136, in format
    message.update(self.get_extra_fields(record))
  File "/usr/local/lib/python2.7/dist-packages/logstash/formatter.py", line 45, in get_extra_fields
    fields[key] = repr(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 19: ordinal not in range(128)
Logged from file logstash.py, line 131

```

The problem comes from the latin1 character present in the handled value.

### PR DESCRIPTION
**Pull request by rrey**
Solves #70.

### CODE REVIEW

**Comment by rrey** [comment]
@vklochan are you still maintaining this repository ? There is no activity for a while now.

**Comment by miso-belica** [comment]
@vklochan is this project actively maintained? Do you have time? Do you need help?

**Comment by vklochan** [comment]
I'm going to catch up with maintenance of the project. I'll review the issue this month.

**Comment by wizardion** [comment]
To avoid encoding issues, and converting values to Unicode, please use this library: `from __future__ import unicode_literals`

**Pull request closed without merging**
